import { images as imgs } from "../../utils/data.ts";

export const stones = [
  {
    name: "Biotite",
    url: imgs.biotite,
    symbol: "Bio",
    source: "IMA–CNMNC",
    formulae: "K(Mg,Fe)<sub>3</sub>AlSi<sub>3</sub>>",
    group: "Phyllosilicate",
  },
  {
    name: "Gemstone",
    url: imgs.gemstone,
    symbol: "Gst",
    source: "Gemological",
    formulae: "Varies",
    group: "Various",
  },
  {
    name: "Muscovite",
    url: imgs.muscovite,
    symbol: "Msc",
    source: "IMA–CNMNC",
    formulae: "KAl<sub>2</sub>(AlSi<sub>3</sub>O<sub>10</sub>)(F,OH)<sub>2</sub>",
    group: "Phyllosilicate"
  },
  {
    name: "Quartz",
    url: imgs.quartz2,
    symbol: "Qtz",
    source: "IMA–CNMNC",
    formulae: "SiO<sub>2</sub>",
    group: "Tectosilicate",
  },
  {
    name: "Beryl",
    url: imgs.berylVertical,  
    symbol: "Brl",
    source: "IMA–CNMNC",
    formulae: "Be<sub>3</sub>Al<sub>2</sub>Si<sub>6</sub>O<sub>18</sub>",
    group: "Cyclosilicate",
  },
  {
    name: "Zinc",
    url: imgs.zinc,
    symbol: "Zn",
    source: "Metal",
    formulae: "IMA–CNMNC",
    group: "Metal",
  },
  {
    name: "Oxyphlogopite",
    url: imgs.oxyphlogopite1,
    symbol: "Oxy",
    source: "IMA–CNMNC",
    formulae: "K(Mg,Fe)<sub>3</sub>AlSi<sub>3</sub>O<sub>10</sub>",
    group: "Phyllosilicate",
  },
  {
    name: "Potosiite",
    url: imgs.potosiite,
    symbol: "Pts",
    source: "IMA–CNMNC",
    formulae: "Ba(Cu<sub>4</sub>(OH)<sub>6</sub>Cl<sub>2</sub>)",
    group: "Halide",
  },
  {
    name: "Halite",
    url: imgs.halite,
    symbol: "Hlt",
    source: "Evaporite",
    formulae: "NaCl",
    group: "Halide",
  },
];