import { images as imgs } from "../../utils/data.ts";

export const stones = [
  {
    name: "Biotite",
    url: imgs.biotite,
    symbol: "Bio",
    source: "IMA–CNMNC",
    formulae: "K(Mg,Fe)<sub>3</sub>AlSi<sub>3</sub>>",
    group: "Phyllosilicate",
  },
  {
    name: "Gemstone",
    url: imgs.gemstone,
    symbol: "Gst",
    source: "Gemological",
    formulae: "Varies",
    group: "Various",
  },
  {
    name: "Quartz2",
    url: imgs.quartz2,
    symbol: "Qtz",
    source: "IMA–CNMNC",
    formulae: "SiO<sub>2</sub>",
    group: "Tectosilicate",
  },
  {
    name: "Feldspar",
    url: imgs.feldspar,
    symbol: "Fsp",
    source: "IMA–CNMNC",
    formulae: "CaAl<sub>2</sub>Si<sub>2</sub>O<sub>8</sub>",
    group: "Tectosilicate",
  },
  {
    name: "Zinc",
    url: imgs.zinc,
    symbol: "Zn",
    source: "Metal",
    formulae: "Zn",
    group: "Metal",
  },
  {
    name: "Oxyphlogopite2",
    url: imgs.oxyphlogopite2,
    symbol: "Oxy",
    source: "IMA–CNMNC",
    formulae: "K(Mg,Fe)<sub>3</sub>AlSi<sub>3</sub>O<sub>10</sub>",
    group: "Phyllosilicate",
  },
  {
    name: "Potosiite",
    url: imgs.potosiite,
    symbol: "Pts",
    source: "IMA–CNMNC",
    formulae: "Ba(Cu<sub>4</sub>(OH)<sub>6</sub>Cl<sub>2</sub>)",
    group: "Halide",
  },
  {
    name: "Oxyphlogopite4",
    url: imgs.oxyphlogopite4,
    symbol: "Oxy",
    source: "IMA–CNMNC",
    formulae: "K(Mg,Fe)<sub>3</sub>AlSi<sub>3</sub>O<sub>10</sub>",
    group: "Phyllosilicate",
  },
  {
    name: "Halite",
    url: imgs.halite,
    symbol: "Hlt",
    source: "Evaporite",
    formulae: "NaCl",
    group: "Halide",
  },
];